import type { CollectionAnalytics } from "@shared/schema";

export class InfographicPromptBuilder {
  static buildCollectionSummary(
    collectionName: string,
    analytics: CollectionAnalytics,
  ): string {
    const overallStats = analytics.overallStats || {
      totalCompletedSessions: 0,
      avgSessionDuration: 0,
      avgQualityScore: 0,
      commonQualityIssues: [],
    };
    const themes = analytics.themes ? [...analytics.themes] : [];

    const topThemes = themes
      .sort((a, b) => (b.verbatims?.length || 0) - (a.verbatims?.length || 0))
      .slice(0, 5)
      .map((t) => t.theme || "Unknown theme");

    const qualityIssues = (overallStats.commonQualityIssues || [])
      .slice(0, 3)
      .map((i) => `${i.flag} (${i.count})`);

    return `Create a professional research infographic.

TITLE: "${collectionName}"
SUBTITLE: "Interview Collection Analytics"

DESIGN REQUIREMENTS:
- Clean, modern, but quirky design. Make it playful, engaging, whilst remaining professional
- Interesting visual elements, including images, icons, and charts
- Cool whites and light greys with confident cobalt-blue accents and soft pastel status tints
- 16:9 landscape orientation
- Clear visual hierarchy

CONTENT SECTIONS:

SECTION 1 - KEY METRICS:
- Total Sessions: ${overallStats.totalCompletedSessions}
- Average Duration: ${Math.round(overallStats.avgSessionDuration)} minutes
- Quality Score: ${Math.round(overallStats.avgQualityScore)}%

SECTION 2 - TOP THEMES:
${topThemes.map((t, i) => `${i + 1}. ${t}`).join("\n")}

SECTION 3 - QUALITY INSIGHTS:
${qualityIssues.length > 0 ? qualityIssues.join(" | ") : "No issues detected"}

FOOTER: "Generated by Alvia | ${new Date().toLocaleDateString()}"

IMPORTANT:
- All text must be clearly readable
- Use icons, images and charts for visual interest
- Maintain consistent spacing and alignment`;
  }

  static buildThemeNetwork(
    collectionName: string,
    themesInput: CollectionAnalytics["themes"],
  ): string {
    const themes = themesInput ? [...themesInput] : [];
    const topThemes = themes
      .sort((a, b) => (b.verbatims?.length || 0) - (a.verbatims?.length || 0))
      .slice(0, 8);

    return `Create a visual network diagram showing research themes.

TITLE: "${collectionName} - Theme Analysis"

DESIGN:
- Modern data visualization style
- Circular nodes of varying sizes
- Node size represents importance/frequency
- Clean, modern, but quirky design. Make it playful, engaging, whilst remaining professional
- Interesting visual elements, including images, icons, and charts
- Cool whites and light greys with confident cobalt-blue accents and soft pastel status tints
- 16:9 landscape orientation
- Clear visual hierarchy

NODES TO DISPLAY:
${topThemes.map((t, i) => `- "${t.theme}" (${t.sentiment || "neutral"} sentiment)`).join("\n")}

VISUAL ELEMENTS:
- Draw connecting lines between related themes
- Use color to indicate sentiment (green=positive, gray=neutral, orange=negative)
- Add a small legend explaining the visualization`;
  }

  static buildKeyFindings(
    collectionName: string,
    analytics: CollectionAnalytics,
  ): string {
    const findings = analytics.keyFindings
      ? [...analytics.keyFindings].slice(0, 5)
      : [];
    const consensus = analytics.consensusPoints
      ? [...analytics.consensusPoints].slice(0, 3)
      : [];
    const divergence = analytics.divergencePoints
      ? [...analytics.divergencePoints].slice(0, 2)
      : [];

    return `Create a key findings summary infographic.

TITLE: "${collectionName} - Key Findings"

DESIGN:
- Clean, modern, but quirky design. Make it playful, engaging, whilst remaining professional
- Interesting visual elements, including images, icons, and charts
- Cool whites and light greys with confident cobalt-blue accents and soft pastel status tints
- 16:9 landscape orientation
- Clear visual hierarchy

CONTENT:

KEY FINDINGS:
${findings.length > 0 ? findings.map((f, i) => `${i + 1}. ${f.finding || "Finding not available"}`).join("\n") : "No key findings identified yet."}

CONSENSUS POINTS (things everyone agrees on):
${consensus.length > 0 ? consensus.map((c) => `• ${c.topic || "Topic"}: ${c.position || "Position not specified"} (${c.agreementLevel || 0}% agreement)`).join("\n") : "No consensus points identified yet."}

${
  divergence.length > 0
    ? `DIVERGENT VIEWS:
${divergence.map((d) => `• ${d.topic || "Topic"}: ${(d.perspectives || []).map(p => `${p.position || "View"} (${p.count || 0} responses)`).join(" vs ")}`).join("\n")}`
    : ""
}

STYLE:
- Use checkmark icons for consensus
- Use split/diverge icons for divergence
- Create visual separation between sections
- All text must be clearly legible`;
  }
}
