import type { CollectionAnalytics } from '@shared/schema';

export class InfographicPromptBuilder {
  static buildCollectionSummary(
    collectionName: string,
    analytics: CollectionAnalytics
  ): string {
    const { overallStats, themes } = analytics;

    const topThemes = themes
      .sort((a, b) => (b.verbatims?.length || 0) - (a.verbatims?.length || 0))
      .slice(0, 5)
      .map(t => t.theme);

    const qualityIssues = overallStats.commonQualityIssues
      .slice(0, 3)
      .map(i => `${i.flag} (${i.count})`);

    return `Create a professional research infographic.

TITLE: "${collectionName}"
SUBTITLE: "Interview Collection Analytics"

DESIGN REQUIREMENTS:
- Clean, modern corporate design
- Navy blue and teal color scheme with white background
- 16:9 landscape orientation
- Professional sans-serif typography
- Clear visual hierarchy

CONTENT SECTIONS:

SECTION 1 - KEY METRICS (display as large stat cards):
- Total Sessions: ${overallStats.totalCompletedSessions}
- Average Duration: ${Math.round(overallStats.avgSessionDuration)} minutes
- Quality Score: ${Math.round(overallStats.avgQualityScore)}%

SECTION 2 - TOP THEMES (display as a ranked list with visual bars):
${topThemes.map((t, i) => `${i + 1}. ${t}`).join('\n')}

SECTION 3 - QUALITY INSIGHTS (display as small badges/tags):
${qualityIssues.length > 0 ? qualityIssues.join(' | ') : 'No issues detected'}

FOOTER: "Generated by Alvia | ${new Date().toLocaleDateString()}"

IMPORTANT:
- All text must be clearly readable
- Use icons or simple graphics for visual interest
- Maintain consistent spacing and alignment
- Create a polished, presentation-ready design`;
  }

  static buildThemeNetwork(
    collectionName: string,
    themes: CollectionAnalytics['themes']
  ): string {
    const topThemes = themes
      .sort((a, b) => (b.verbatims?.length || 0) - (a.verbatims?.length || 0))
      .slice(0, 8);

    return `Create a visual network diagram showing research themes.

TITLE: "${collectionName} - Theme Analysis"

DESIGN:
- Modern data visualization style
- Circular nodes of varying sizes
- Node size represents importance/frequency
- Soft gradients from teal to blue
- Clean white or light gray background
- 16:9 landscape orientation

NODES TO DISPLAY:
${topThemes.map((t, i) => `- "${t.theme}" (${t.sentiment || 'neutral'} sentiment)`).join('\n')}

VISUAL ELEMENTS:
- Draw connecting lines between related themes
- Use color to indicate sentiment (green=positive, gray=neutral, orange=negative)
- Add a small legend explaining the visualization

STYLE:
- Professional infographic aesthetic
- Clear, readable labels on all nodes
- Subtle grid or dot pattern background`;
  }

  static buildKeyFindings(
    collectionName: string,
    analytics: CollectionAnalytics
  ): string {
    const findings = analytics.keyFindings?.slice(0, 5) || [];
    const consensus = analytics.consensusPoints?.slice(0, 3) || [];
    const divergence = analytics.divergencePoints?.slice(0, 2) || [];

    return `Create a key findings summary infographic.

TITLE: "${collectionName} - Key Findings"

DESIGN:
- Clean editorial style
- Navy and white color scheme with accent colors
- 16:9 landscape orientation
- Icon-based visual elements

CONTENT:

KEY FINDINGS:
${findings.map((f, i) => `${i + 1}. ${f.finding}`).join('\n')}

CONSENSUS POINTS (things everyone agrees on):
${consensus.map(c => `• ${c.point}`).join('\n')}

${divergence.length > 0 ? `DIVERGENT VIEWS:
${divergence.map(d => `• ${d.point}`).join('\n')}` : ''}

STYLE:
- Use checkmark icons for consensus
- Use split/diverge icons for divergence
- Create visual separation between sections
- All text must be clearly legible`;
  }
}
